### ISSUE TITLE
beta-service.geonet.org.nz dataselect query problem

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#107]
I have just been querying the archive FDSN service, beta-service.geonet.org.nz, and I can't access recent waveform data (since 17/8/2017).

**Comment by nbalfour** [comment]
Sorry, it now seems to be fixed.

**Comment by gclitheroe** [comment]
it's not all the way fixed - I'm working on it.

* I have to do the reindex of the stuff that's missing (this is part way done which is why it looks like it's working again)
* document how to reindex
* figure out why this stopped working in the first place and fix any bugs
* add some service monitoring

**Comment by gclitheroe** [comment]
This is fixed.  217.277 went in correctly.
