### ISSUE TITLE
Comparing CWB and FDSN

### ISSUE THREAD

**Issue by cvanhoutte** [GeoNet/fdsn#147]
Hi there

I'm transitioning to the obspy FDSN client for downloading data, but I occasionally come across some problems. For example, I get two very different outputs when I use the CWB command and the FDSN client through obspy.

These codes usually works fine for both clients, but occasionally things go awry for the FDSN client. In the case below, the FDSN client gives me 76 different traces instead of a single trace. Another day where this happens is 2013/04/10, where the FSDN client splits the day into two traces. There don't appear to be any issues with the waveforms that come from the CWB client.

Can you please advise which one is correct?

Thanks
Chris
________________________
CWB Client:

java -jar GeoNetCWBQuery-4.2.0-bin.jar -b "2013/04/22 00:00:00" -s "NZWIZ..HHN" -d 86400 -o NZ_WIZ_HHN_2013_112.SAC

FDSN Client:

import datetime
from obspy.clients.fdsn import Client as FDSN_Client
from obspy import read
client = FDSN_Client("GEONET")
st = client.get_waveforms(network='NZ', station='WIZ', location='*',
                          channel='HHN', starttime=datetime.datetime(2013, 4, 22, 0, 0),
                          endtime=datetime.datetime(2013, 4, 23, 0, 0))
st.write("NZ_WIZ_HHN_2013_112.SAC", format='SAC')

**Comment by ozym** [comment]
Chris,

This appears to be a back-end data problem rather than an FDSN problem per se.

It appears that a few days worth of data for that station where corrupted in 2013. Days, 112 - 114 & 126. The other days seem to be okay. The usual cause for this is another instrument being turned on with the wrong settings and quietly recording data pretending to be from elsewhere, usually this isn't the online system but via an archive to disk somewhere. This data then gets merged together (with the good data) to cause the problem. Another cause is a faulty clock which can create data for the wrong time and overwrite good data, which doesn't seem to be the case here.

The CWB system doesn't have a back-fill mechanism so it will usually only have the real-time feed and in  this example will not have been corrupted by later arriving data.

I expect we will get some form of automatic check going to compare the two systems and isolate any inconsistencies, most likely by looking at the existing files and detecting those that have a large number of gaps (as pre above).

Mark

**Comment by cvanhoutte** [comment]
Ok great, thanks for that Mark. Would you suggest that I continue to use the CWB in the meantime, or is the fdsn system still less error-prone?
Chris

**Comment by ozym** [comment]
I'd suggest moving to FDSN as we are planning to move off of CWB when the hardware reaches its end of life.
