### ISSUE TITLE
Why would nrt service drop off from time to time?

### ISSUE THREAD

**Issue by ddempsey** [GeoNet/fdsn#192]
Hi all,

I have an application that regularly requests new data for a particular GeoNet station (WIZ) using either the regular or nrt service. Usually, the nrt service has data up to 20 or 30 minutes behind real time which is perfect. However, I've noticed with this station that every week or so it falls behind. For example, right now (10am 27-07-2020 NZ time) the nrt service is about 14 hours behind real time for WIZ. These episodes usually last 24 hours or so before it goes back to near real-time with "missing" data available again. Any ideas why this might happen?

I usually use ObsPy to download data but I have checked e.g. the command below also produces an incomplete data return

`curl "https://service-nrt.geonet.org.nz/fdsnws/dataselect/1/query?network=NZ&station=WIZ&location=10&channel=HHZ&starttime=2020-07-26T00:00:00&endtime=2020-07-26T23:00:00" -o test.mseed`

Edit: I have checked with the Volcano Monitoring Group at GNS who use the same station, there is no corresponding interruption with their feed, but then I don't think they use FDSN.

Cheers
David

**Comment by salichon** [comment]
Hi @ddempsey 
Will  follow up on this
Does it still occur for WIZ ? 
This might be related to  data transmission delay - Also since this site is less closely maitained with regards to their position on white island, this might occur periodically also these days.

Besides,  a lot of effort has been put to improve the FDSN  service end 2020,  this could have helped a bit too 

thanks for your feedback,

NB: If you need real time streaming i would recommend the seedlink 

Cheers
jerome

**Comment by salichon** [comment]
Kia Ora @ddempsey 
Are you still affected by some sort of drop off on the fdsn-nrt ? 
We are always interest in some feed back, thanks.
If not  I  propose to close this ticket
cheers 
regards
jerome

**Comment by ddempsey** [comment]
Thanks for the follow up, Jerome. I came up with a workaround so haven't been suffering any issues, nor can I say if the underlying issue still exists since your improvements. Probably a good idea to close. Cheers
