### ISSUE TITLE
Time handling for station service - tests needed

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#47]
We're making progress - the time parsing from swarm now works but I think the result set might not be correct.

If I query 

```
http://beta-service.geonet.org.nz/fdsnws/station/1/query?&format=text&level=channel&network=NZ&starttime=2017-06-01T04:08:18.636
```

I get no stations - I expect to get all the stations that are open "now".  

If I query 

```
http://beta-service.geonet.org.nz/fdsnws/station/1/query?&format=text&level=channel&network=NZ&starttime=2015-06-01T04:08:18.636
```

I get a small set of stations.  Is the query currently returning stations that change from closed to open instead of stations that are open at the time (but maybe opened earlier)?

**Comment by nbalfour** [comment]
I've just done a bit more investigating. 

The site WTMC opened 2005-11-15 according to Delta and has been open ever since. 

If I query
`http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&starttime=2005-01-01T00:00:00`

It returns the site information

If I query
`http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&starttime=2015-01-01T00:00:00`

I get nothing, not even an error. If I do the same query in obspy I get an error "FDSNException: No data available for request"

It seems to be that if the site is opened after the start time it will return the site information.  However, if it is opened prior to the start time it won't be.  

If my brain is working correctly (no guarantees) the rule should be something like this...
- If a site is opened prior to the endtime and closed after the starttime then it is included.

**Comment by gclitheroe** [comment]
I've merged PR49.  It might fix this and it will let the users test it out.

I've reopened this as it would be ideal if we could come up with some tests to prove this is working.  This will involve coming up with some input and the expected output for that input.  It's pretty complicated and will need some help.

**Comment by nbalfour** [comment]
@gclitheroe, by input do you mean the source StationXML or the query or both?

**Comment by rumachan** [comment]
Initial check using swarm suggests time handling is okay. I can see a list of all available channels, select one and swarm starts to plot those data as a drumplot.
There seems to be some issues related to using swarm with FDSN. I'll document those later, once I've done some more testing.

**Comment by gclitheroe** [comment]
@nbalfour - yes some input station XML files that we know the expected result for would be ideal.

**Comment by gclitheroe** [comment]
@rumachan would you be able to try swarm using the IRIS FDSN WS?  http://service.iris.edu/fdsnws/

I had a quick go and it didn't seem to work very well for me.

**Comment by rumachan** [comment]
@gclitheroe once I selected the correct network with IRIS (used NZ) it works fine. A day of URZ HHZ data loads in about 45 sec. And interaction with those data is quick. The same data fed from our Winston loads in ~2 sec, because it has pre-decimated data available.

Response with our beta FDSN seems varied. At home, this morning, I got many error messages about not being able to get data, or slow response, but I did actually load some 2016 data. But later from the office I've had no success loading anything from beta FDSN in swarm - just hangs. Though recognition of what channels are available work fine.

**Comment by rumachan** [comment]
@gclitheroe Have tried Swiss and Southern California stations using FDSN into swarm - acceptably fast for current data, 10-15 sec to load a day, getting HHZ.

**Comment by rumachan** [comment]
And using ObsPy I can load the same data from both service and beta-service in ~2 secs. These are the data swarm is hanging on.

**Comment by mabznz** [comment]
After talking with @gclitheroe it could be good to replace the data source for beta with the present production data.
That would be:

`curl -s "http://service.geonet.org.nz/fdsnws/station/1/query" | xmllint --format - > prod_station.xml`

If that could be used for beta instead of the stationxml that is manually generated out of the new Delta system, then we are testing the code and not the  data which we know is not the same at present.

Then we could do some diffs for thinks like the below. Hope that makes sense. Who can replace that station xml file on FDSN beta? 

```
byron@byron-Latitude-E7250:~$ curl -s "http://service.geonet.org.nz/fdsnws/station/1/query?station=WTMC" | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.0">
  <Source>SeisComP3</Source>
  <Sender>WEL(GNS_Secondary)</Sender>
  <Created>2017-06-06T04:02:50</Created>
  <Network code="NZ" startDate="1980-01-01T00:00:00" restrictedStatus="open">
    <Description>New Zealand National Seismograph Network</Description>
    <Station code="WTMC" startDate="2005-11-15T00:00:00" restrictedStatus="open">
      <Latitude>-42.619455</Latitude>
      <Longitude>173.053596</Longitude>
      <Elevation>198</Elevation>
      <Site>
        <Name>Te Mara Farm Waiau</Name>
      </Site>
      <CreationDate>2005-11-15T00:00:00</CreationDate>
    </Station>
  </Network>
</FDSNStationXML>
```

```
byron@byron-Latitude-E7250:~$ curl -s "http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC" | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1">
  <Source>GeoNet</Source>
  <Sender>WEL(GNS_Test)</Sender>
  <Module>Delta</Module>
  <Created>2017-05-24T14:14:25Z</Created>
  <Network code="NZ" startDate="1884-02-01T00:00:00" restrictedStatus="open">
    <Description>New Zealand National Seismograph Network</Description>
    <TotalNumberStations>2199</TotalNumberStations>
    <SelectedNumberStations>1</SelectedNumberStations>
    <Station code="WTMC" startDate="2005-11-15T00:00:00" restrictedStatus="open">
      <Description>Canterbury regional strong motion network</Description>
      <Comment>
        <Value>Location is given in WGS84</Value>
      </Comment>
      <Latitude datum="WGS84">-42.619455176</Latitude>
      <Longitude datum="WGS84">173.053596231</Longitude>
      <Elevation>198</Elevation>
      <Site>
        <Name>Te Mara Farm Waiau</Name>
        <Description>within 5 km of Waiau</Description>
      </Site>
      <CreationDate>2005-11-15T00:00:00Z</CreationDate>
      <TotalNumberChannels>15</TotalNumberChannels>
      <SelectedNumberChannels>15</SelectedNumberChannels>
    </Station>
  </Network>
</FDSNStationXML>
```

**Comment by mabznz** [comment]
@junghao 
Ok have my test sorted with known input and output. There is an issue in channels being returned when specifying times. This may the problem with Stage elements not appearing. Here start time is specified so only one channel element (the current one) should be returned.

http://service.geonet.org.nz/fdsnws/station/1/query?station=ARHZ&channel=EHE&location=10&starttime=2012-01-20T22:30:01&level=response

Gives

```
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.0">
<Source>SeisComP3</Source>
<Sender>WEL(GNS_Secondary)</Sender>
<Created>2017-06-19T04:10:14</Created>
<Network code="NZ" startDate="1980-01-01T00:00:00" restrictedStatus="open">
<Description>New Zealand National Seismograph Network</Description>
<Station code="ARHZ" startDate="2010-03-11T00:00:00" restrictedStatus="open">
<Latitude>-39.2631</Latitude>
<Longitude>176.9959</Longitude>
<Elevation>270</Elevation>
<Site>...</Site>
<CreationDate>2010-03-11T00:00:00</CreationDate>
<Channel code="EHE" startDate="2012-01-19T22:30:01" restrictedStatus="open" locationCode="10">...</Channel>
</Station>
</Network>
</FDSNStationXML>
```

Returns one channel in array while beta returns two:

http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=ARHZ&channel=EHE&location=10&starttime=2012-01-20T22:30:01&level=response

Gives
```
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1">
<Source>GeoNet</Source>
<Sender>WEL(GNS_Test)</Sender>
<Module>Delta</Module>
<Created>2017-05-24T14:14:25Z</Created>
<Network code="NZ" startDate="1884-02-01T00:00:00" restrictedStatus="open">
<Description>New Zealand National Seismograph Network</Description>
<TotalNumberStations>2199</TotalNumberStations>
<SelectedNumberStations>1</SelectedNumberStations>
<Station code="ARHZ" startDate="2010-03-11T00:00:00" restrictedStatus="open">
<Description>Hawke's Bay regional seismic network</Description>
<Comment>...</Comment>
<Latitude datum="WGS84">-39.2631</Latitude>
<Longitude datum="WGS84">176.9959</Longitude>
<Elevation>270</Elevation>
<Site>...</Site>
<CreationDate>2010-03-11T00:00:00Z</CreationDate>
<TotalNumberChannels>6</TotalNumberChannels>
<SelectedNumberChannels>2</SelectedNumberChannels>
<Channel code="EHE" startDate="2010-03-11T21:16:00" endDate="2012-01-19T22:29:01" restrictedStatus="open" locationCode="10">...</Channel>
<Channel code="EHE" startDate="2012-01-19T22:30:01" restrictedStatus="open" locationCode="10">...</Channel>
</Station>
</Network>
</FDSNStationXML>
```

**Comment by gclitheroe** [comment]
fix  from @junghao has been deployed

**Comment by mabznz** [comment]
This fixed the multiple channels returned issue. Now this just returns just the one channel as expected.

http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=ARHZ&channel=EHE&location=10&starttime=2012-01-20T22:30:01&level=response

Still and issue around #62
