### ISSUE TITLE
beta station query does not recognise "includepicks" parameter

### ISSUE THREAD

**Issue by filefolder** [GeoNet/fdsn#81]
https://beta-service.geonet.org.nz/fdsnws/event/1/query?starttime=1970-02-01&endtime=1975-12-31&maxdepth=100&includepicks=true

seems to give "schema: invalid path "includepicks" " regardless of format

**Comment by nbalfour** [comment]
includepicks is not a valid parameter according to the FDSN specifications. Do you mean includearrivals?

**Comment by filefolder** [comment]
didn't try includarrivals.. i'm just going by what's listed at http://service.geonet.org.nz/fdsnws/event/1/ 

additional request parameters, effective only for xml output:
includecomments: boolean, default: true
includepicks: boolean, default: false
formatted: boolean, default: false

(the beta version of that page isn't up.. i assume it'd be more or less the same, however)

**Comment by nbalfour** [comment]
You can refer to the wadl for the service to find the supported parameters http://beta-service.geonet.org.nz/fdsnws/event/1/application.wadl 
The full description of the FDSN specifications can be found here https://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf

The service http://service.geonet.org.nz/fdsnws/event/1/ has never been operational but the page shows up because we have the other two services: dataselect and station. Note: this (service.geonet.org.nz) is a SeisComP3 implementation of FDSN webservices. The beta is not using SC3 and is based off the documented specifications. 

I am planning to update the FDSN webpage later this week to list supported parameters.
